version: '3'

services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"

  app:
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/omicsdb

  seeder:
    build:
      context: .
    depends_on:
      - mongodb
      - app
    command: ["node", "seeder.js"]
    environment:
      MONGO_URI: mongodb://mongodb:27017/omicsdb